### ISSUE TITLE
Nextcloud activation

### ISSUE THREAD

**Issue by ronbass** [Zimbra/zimbra-zimlet-nextcloud#2]
It seems that the ACTIVATE button doesn't give the right access.
It opens the Nexcloud login page and after giving the authorization it opens a new modern UI webmail page and in the Nextcloud tab, the button Activate is still there.
So no access to the files is being given.
After few times trying I can't login to NC and I have to purge the DB from my IP address to login.

![image](https://user-images.githubusercontent.com/53493239/188528199-82f064f9-8be3-4fa4-bfdd-d26b2c13b254.png)
![image](https://user-images.githubusercontent.com/53493239/188528229-3f8ab298-d561-46e0-a3b2-6528ee9bae2a.png)

**Comment by ghost** [comment]
Follow the steps from here: https://zimbra.github.io/zimbra-9/adminguide.html#_setting_up_nextcloud

zimbraOAuthConsumerAPIScope holds the URL to your Nextcloud instance, in our example we have set-up Nextcloud in a folder /nextcloud on [nextcloud.server.com](http://nextcloud.server.com/). If your Nextcloud is installed directly in the root / of your domain, make sure to use 'https://nextcloud.server.com/index.php:nextcloud_noop' as zimbraOAuthConsumerAPIScope
