### ISSUE TITLE
Zimbra wiriting zero Length Files to Nextcloud

### ISSUE THREAD

**Issue by sifupanton** [Zimbra/zimbra-zimlet-nextcloud#3]
Greetings,  we have successfully setup zimbra and nextcloud however not all features work. 
1. We can select files from nextcloud and attach to messages ok
2. We can attempt to save an email attachment to nextcloud and zimbra says "saved to nextcloud". However when we check nextcloud the attachment filename is there ok but it's length is 0 bytes. This happen with any type of attachment. Effectively the file contents have not been transferred from zimbra to nextcloud.
Please advise how to possibly fix.

**Comment by ghost** [comment]
This issue has been identified, and only affects conversation view on Modern UI. This is fixed in the next release.

**Comment by MisTerM7** [comment]
Zimbra 10 compatible?
