### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Marvellvs** [Zimbra/zimbra-zimlet-nextcloud#9]
Hi! How I can install this extension?

I'm install zimbra via official docs (install.sh), but I can't find in repo needed package
<img width="523" alt="image" src="https://github.com/Zimbra/zimbra-zimlet-nextcloud/assets/37035356/d4f22cfb-f1c5-4a19-973a-90618b0ada8f">

And where I try build from source, I have next error :
<img width="1071" alt="image" src="https://github.com/Zimbra/zimbra-zimlet-nextcloud/assets/37035356/392c4210-0410-427f-b1f3-e3835bea4809">

**Comment by ghost** [comment]
This Zimlet is available on Zimbra 10 Network Edition.

https://zimbra.github.io/documentation/zimbra-10/adminguide.html#_setting_up_nextcloud
